{% set name = "voila" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dbca66019d84e0ec24696b715ca16b447bf479b99b7ff83c5f778c55f2284f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs <16
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.8.1
  run:
    - python >=3.7
    - nbconvert >=6.4.5,<8
    - jupyter_core >=4.11.0
    - jupyterlab_server >=2.3.0,<3
    - jupyter_client >=6.1.3,<=9
    - jupyter_server >=1.18,<3
    - nbclient >=0.4.0,<0.8
    - websockets >=9
    - traitlets >=5.0.3,<6

test:
  imports:
    - voila
  commands:
    - voila --help
    - test -f ${PREFIX}/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@voila-dashboards\\jupyterlab-preview\\package.json (exit 1)          # [win]


about:
  home: https://github.com/voila-dashboards/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Rendering of live Jupyter notebooks with interactive widgets
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/voila-dashboards/voila

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
    - trungleduc
    - martinRenou
