{% set name = "voila" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 332725b88fb026ad421db90fdad53d7e8de2ffd03a8584a55d9940465932ede8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
  run:
    - python >=3.6
    - nbconvert >=6.0.0,<7
    - jupyter_server >=0.3.0,<2
    - nbclient >=0.4.0,<0.6

test:
  imports:
    - voila
  commands:
    - voila --help

about:
  home: https://github.com/voila-dashboards/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Rendering of live Jupyter notebooks with interactive widgets
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/voila-dashboards/voila

outputs:
  - name: voila
    version: {{ version }}
    files:
      - "lib/python{{ PY_VER }}/site-packages/voila"
  - name: voila-sourcemaps
    version: {{ version }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('voila', exact=True) }}
    script: install_sourcemaps.sh


extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
