{% set name = "voila" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 640acadb6e787370f32a5264e0f644c0bcb0d0c8026823f6d296cea725c6b289

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs <16
    - jupyter-packaging >=0.10,<1
  run:
    - python >=3.7
    - nbconvert >=6.4.2,<7
    - jupyterlab_server >=2.3.0,<3
    - jupyter_client >=6.1.3,<8
    - jupyter_server >=0.3.0,<2
    - nbclient >=0.4.0,<0.6
    - websockets >=9
    - traitlets >=5.0.3,<6
  run_constrained:
    - ipywidgets <8

test:
  imports:
    - voila
  commands:
    - voila --help


about:
  home: https://github.com/voila-dashboards/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Rendering of live Jupyter notebooks with interactive widgets
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/voila-dashboards/voila

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
    - trungleduc
    - martinRenou
